name:                HexGame
version:             0.1.0.0
github:              "Halloneo/HexGame"
license:             BSD3
author:              "Halloneo"
maintainer:          "Halloneo"
copyright:           "2020 Halloneo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Halloneo/HexGame#readme>

dependencies:
- base >= 4.7 && < 5
- random
- containers
- MonadRandom
- transformers
- aeson
- servant
- servant-server
- servant-client
- servant-swagger
- servant-swagger-ui
- swagger2
- stm
- wai
- http-client
- lens
- uuid
- warp
- options
- streaming-commons
- ttrie
- time
- lzma

library:
  source-dirs: src

executables:
  HexGame-server:
    main:                Main.hs
    source-dirs:         app/server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HexGame

  HexGame-client:
    main: Main.hs
    source-dirs: app/client
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HexGame

tests:
  HexGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HexGame
